model_list:
  - model_name: github/gpt-4.1
    litellm_params:
      model: github/gpt-4.1
      api_key: os.environ/GITHUB_COPILOT_TOKEN
      extra_headers:
        editor-version: os.environ/COPILOT_EDITOR_VERSION
        Copilot-Integration-Id: os.environ/COPILOT_INTEGRATION_ID

  - model_name: github/gpt-4o
    litellm_params:
      model: github/gpt-4o
      api_key: os.environ/GITHUB_COPILOT_TOKEN
      extra_headers:
        editor-version: os.environ/COPILOT_EDITOR_VERSION
        Copilot-Integration-Id: os.environ/COPILOT_INTEGRATION_ID

general_settings:
  master_key: os.environ/LITELLM_MASTER_KEY

litellm_settings:
  drop_params: true
  set_verbose: false
